name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter pub global activate dartdoc
      - run: dart doc
      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: dartdoc
          path: doc/api
      - run: flutter pub global activate coverage
      - run: flutter test --coverage
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/lcov.info
